version: 3.3.7.{build}
image: Visual Studio 2017
build_script:
- ps: build\build.ps1 -Script build\build.cake -Target Build-Assembly
test_script:
- ps: build\build.ps1 -Script build\build.cake -Target Run-Tests
